/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MessageBoard__factory } from "./MessageBoard__factory";
export { SimpleNFT__factory } from "./SimpleNFT__factory";
export { SimpleToken__factory } from "./SimpleToken__factory";
