/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MessageBoard } from "./MessageBoard";
export type { SimpleNFT } from "./SimpleNFT";
export type { SimpleToken } from "./SimpleToken";
